image: gcc:latest

stages:
  - build
  - test

cache:
  paths:
    - bin/
    - packup
    - packup_*

job_build:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq valgrind gtk+-3 cmake
    - git clone --recursive https://github.com/Snaipe/Criterion && cd Criterion && mkdir build &&  cd build && cmake .. && cmake --build . && make install && cd ../..

  script:
    - pwd
    - make clean
    - make
    - make tests/*
    
job_test:
  stage: test
  before_script:
    - apt-get update -qq && apt-get install -y -qq valgrind gtk+-3 cmake
    - git clone --recursive https://github.com/Snaipe/Criterion && cd Criterion && mkdir build &&  cd build && cmake .. && cmake --build . && make install && cd ../..
  script:
    - ./packup

