image: cedricfarinazzo/archlinux-criterion-c:latest

stages:
  - build
  - test
  - webhook
  
before_script:
  - pacman -Syyu --noconfirm


##################
# BUILD STAGE
job_build_gcc:
  stage: build
  artifacts:
    untracked: true
  variables:
      CC: gcc
  script:
    - make CC=${CC}
    - make tests/* CC=${CC}

job_build_clang:
  stage: build
  artifacts:
    untracked: true
  variables:
      CC: clang
  script:
    - make CC=${CC}
    - make tests/* CC=${CC}


################
# TEST STAGE 
# GCC
job_test_main_gcc:
  stage: test
  dependencies: 
    - job_build_gcc
  script:
    - ./packup --version
  allow_failure: true

job_test_criterion_gcc:
  stage: test
  dependencies: 
    - job_build_gcc
  script:
    - ls | grep -e "packup_test_[a-z]*$" --color=never | sed -e 's/^/.\//' | sh

# CLANG
job_test_main_clang:
  stage: test
  dependencies: 
    - job_build_clang
  script:
    - ./packup --version
  allow_failure: true

job_test_criterion_clang:
  stage: test
  dependencies: 
    - job_build_clang
  script:
    - ls | grep -e "packup_test_[a-z]*$" --color=never | sed -e 's/^/.\//' | sh


#############
# WEBHOOK STAGE
job_success:
    stage: webhook
    script:
        - make clean
        - wget https://gitlab.com/cedricfarinazzo/gitlab-ci-discord-webhook/raw/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL
    when: on_success


job_failure:
    stage: webhook
    script:
        - make clean
        - wget https://gitlab.com/cedricfarinazzo/gitlab-ci-discord-webhook/raw/master/send.sh
        - chmod +x send.sh
        - ./send.sh failure $WEBHOOK_URL
    when: on_failure
