image: cedricfarinazzo/archlinux-criterion-c:latest

stages:
  - build
  - test

cache:
  paths:
    - bin/
    - packup
    - packup_*

job_build:
  stage: build
  before_script:
    - pacman -Syyu --noconfirm
  script:
    - pwd
    - make clean
    - make
    - make tests/*

job_test:
  stage: test
  before_script:
    - pacman -Syyu --noconfirm
  script:
    - ./packup
    - ls | grep -e "packup_test_[a-z]*$" --color=never | sed -e 's/^/.\//' | sh
    - rm -rf Criterion

