image: cedricfarinazzo/archlinux-criterion-c:latest

stages:
  - build
  - test
  - webhook

cache:
  paths:
    - bin/
    - packup
    - packup_*

job_build_gcc:
  stage: build
  before_script:
    - pacman -Syyu --noconfirm
  variables:
      CC: gcc
  script:
    - pwd
    - make clean
    - make CC=${CC}
    - make tests/* CC=${CC}

job_build_clang:
  stage: build
  before_script:
    - pacman -Syyu --noconfirm
  variables:
      CC: clang
  script:
    - pwd
    - make clean
    - make CC=${CC}
    - make tests/* CC=${CC}

job_test:
  stage: test
  before_script:
    - pacman -Syyu --noconfirm
  script:
    - ./packup
    - ls | grep -e "packup_test_[a-z]*$" --color=never | sed -e 's/^/.\//' | sh
    - make clean

job_success:
    stage: webhook
    script:
        - wget https://gitlab.com/cedricfarinazzo/gitlab-ci-discord-webhook/raw/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL
    when: on_success


job_failure:
    stage: webhook
    script:
        - wget https://gitlab.com/cedricfarinazzo/gitlab-ci-discord-webhook/raw/master/send.sh
        - chmod +x send.sh
        - ./send.sh failure $WEBHOOK_URL
    when: on_failure

