# Generated by Django 2.1.7 on 2019-05-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='enc_type',
            field=models.CharField(choices=[('None', 'None'), ('Rotn', 'Rotn'), ('Vigenere', 'Vigenere'), ('AES', 'AES'), ('RSA', 'RSA'), ('Elgamal', 'Elgamal')], default='None', max_length=11),
        ),
    ]
