# Generated by Django 2.1.7 on 2019-05-20 16:15

from django.db import migrations, models
import django.db.models.deletion
import ps4.models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('Archive part', 'Archive part'), ('Public key', 'Public key'), ('Private key', 'Private ley')], default='Archive part', max_length=25)),
                ('backupfile', models.FileField(upload_to=ps4.models.make_filepath)),
                ('filename', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='backup',
            name='backup',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='filename',
        ),
        migrations.AddField(
            model_name='backup',
            name='pass_backup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupfile',
            name='backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps4.Backup'),
        ),
    ]
