# Generated by Django 2.1.7 on 2019-05-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0002_backup_enc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
