# Generated by Django 2.1.7 on 2019-05-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0003_auto_20190518_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup',
            old_name='date',
            new_name='date_created',
        ),
    ]
