# Generated by Django 2.1.7 on 2019-05-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0005_storageuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageuser',
            name='usage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
