# Generated by Django 2.1.7 on 2019-05-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4', '0006_auto_20190518_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='filename',
            field=models.TextField(blank=True, null=True),
        ),
    ]
